"""initial session log schema

Revision ID: b2ba556c3b77
Revises:
Create Date: 2026-09-10 19:03:26.862416

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2ba556c3b77"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_seen_ns", sa.BigInteger(), nullable=False),
        sa.Column("last_seen_ns", sa.BigInteger(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("AGENT", "HUMAN", "UNKNOWN", name="source", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("site_version", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lure_hits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("lure_id", sa.String(length=64), nullable=False),
        sa.Column("request_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lure_hits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lure_hits_session_id"), ["session_id"], unique=False)

    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("ts_ns", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("path", sa.String(length=2048), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("headers", sa.JSON(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("referrer", sa.String(length=2048), nullable=True),
        sa.Column("hash_ip", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_requests_hash_ip"), ["hash_ip"], unique=False)
        batch_op.create_index(batch_op.f("ix_requests_path"), ["path"], unique=False)
        batch_op.create_index(batch_op.f("ix_requests_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_requests_ts_ns"), ["ts_ns"], unique=False)

    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("framework", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_session_id"), ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_session_id"))

    op.drop_table("runs")
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requests_ts_ns"))
        batch_op.drop_index(batch_op.f("ix_requests_session_id"))
        batch_op.drop_index(batch_op.f("ix_requests_path"))
        batch_op.drop_index(batch_op.f("ix_requests_hash_ip"))

    op.drop_table("requests")
    with op.batch_alter_table("lure_hits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lure_hits_session_id"))

    op.drop_table("lure_hits")
    op.drop_table("sessions")
    # ### end Alembic commands ###
